export {
  appState,
  setAppState,
  workerBridge,
  connectionManager,
  registry,
  logViewerService,
  setWorkerBridge,
  setConnectionManager,
  setRegistry,
  setLogViewerService,
  addPlotTab,
  deletePlotTab,
  renamePlotTab,
  reorderPlotTabs,
  setActiveSubTab,
  type AppState,
} from './app-store';
